<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_title</name>
   <tag></tag>
   <elementGuidId>6906d1d6-9cf3-4592-b1ca-a10c63b304df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//head/title[contains(text(),'Software')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
